- name: mysql
  hosts: all
  become: yes
  tasks:
    - name: Install mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: Enable mysql server service
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: yes

    - name: Root password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1