- name: mysql
  hosts: all
  become: yes
  tasks:
    - name: Installing mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: Start mysql server service
      ansible.builtin.systemd_service:
        name: mysqld
        state: started

    - name: Enable mysql server service
      ansible.builtin.systemd_service:
        name: mysqld
        enabled: true

    - name: Root password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1



